[project]

name = "pyfractions"  # Required


version = "1.0.0"  # Required
requires-python = ">=3.7"

license = {file = "LICENSE"}

[build-system]

requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"